# Generated by Django 3.0.1 on 2019-12-26 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='date_of_birth',
        ),
    ]
